name: Deploy Server

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: ‘openjdk’

    - name: Build and deploy
      run: |
        ./gradlew :server:buildFatJar
        scp ./server/build/libs/server_fat.jar krushiler@213.183.53.46:/home/krushiler/aftermath/server/build
        ssh krushiler@213.183.53.46 "pkill -f server_fat.jar; java -jar /home/krushiler/aftermath/server/build/server_fat.jar"
